version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4    
    restart: always
    ports:
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com    
      PGADMIN_DEFAULT_PASSWORD: admin      
    depends_on:
      - postgres    

  postgres:
    image: postgres:14    
    restart: always
    environment:
      POSTGRES_DB: name_database    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin      
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  pgadmin-data: